* Trivial changes in stream, mencoder, bonnie * Reworked but untested dhrystone and whetstone * Added untested usb-flash-drive test * Minor reworking of hdd-array
git-svn-id: svn+ssh://svn.code.sf.net/p/inq/svn/trunk@434 74654560-fcd8-4db3-b3c5-4c63e7cb38b4

diff --git a/client/test/dhrystone b/client/test/dhrystone
--- a/client/test/dhrystone
+++ b/client/test/dhrystone
@@ -6,60 +6,32 @@
 # VERSION=0.1
 # TAGS=benchmark,cpu
 # VAR=DURATION:int:30:Benchmark duration (sec)
-# VAR=CHECKTIME:int:50:Time between checks of alive benchmarks
 
 . /usr/share/inquisitor/functions-test
 
 RESULT_FILE=`mktemp`
 
-detect_cpu_quantity()
+print_red_message '!!! THIS IS DEVELOPMENT TEST !!!'
+
+# Cleanup
+exit_handler()
 {
-	CPU_QUANTITY=`grep processor /proc/cpuinfo | wc -l`
-}
+	local rc=$?
+	trap - EXIT
 
-start_benchmarking()
-{
-	for i in `seq 1 $CPU_QUANTITY`; do
-		dhrystone $DURATION 2>&1 | awk '{print $1}' > \
-			${RESULT_FILE}${i} &
-		echo $$ > ~/dhrystone$i.pid
-	done
-}
-
-parse_results()
-{
-	for i in `seq 1 $CPU_QUANTITY`; do
-		echo -n "cpu"${i}"="`cat ${RESULT_FILE}${i}`\& >> \
-			${RESULT_FILE}_parsed
-	done
-}
-
-clean_up_after_benchmark()
-{
-	for i in `seq 1 $CPU_QUANTITY`; do
-		rm -f ${RESULT_FILE}${i}
-	done
-	rm -f ${RESULT_FILE}_parsed
-}
-
-detect_cpu_quantity
-start_benchmarking
-
-test_started 1
-
-while true; do
-	sleep $CHECKTIME
-	
-	ALIVE=0
-	for i in `seq 1 $CPU_QUANTITY`; do
-		(( `ps \`cat ~/dhrystone$i.pid\` | wc -l` == 2 )) && \
-			ALIVE=$(( $ALIVE + 1 ))
-	done
-	if [ $ALIVE -eq 0 ]; then
-		parse_results
-		break
+	if [ -f "$RESULT_FILE" ]; then
+		rm -f $RESULT_FILE
 	fi
-done
 
-test_succeeded `cat ${RESULT_FILE}_parsed`
-clean_up_after_benchmark
+	exit $rc
+}
+trap exit_handler HUP PIPE INT QUIT TERM EXIT
+
+CPU_QUANTITY=`grep processor /proc/cpuinfo | wc -l`
+
+for i in `seq 0 $(($CPU_QUANTITY - 1))`; do
+	echo -n "Dhrystone on core $i"
+	taskset -c $i dhrystone $DURATION > $RESULT_FILE
+	echo_success
+	benchmark_submit_float "Core $i loops" `awk '{print $1}' < $RESULT_FILE`
+done
diff --git a/client/test/hdd-array b/client/test/hdd-array
--- a/client/test/hdd-array
+++ b/client/test/hdd-array
@@ -6,32 +6,84 @@
 # POWEROFF_DURING_TEST=false
 # VERSION=0.1
 # TAGS=hdd,stress
-# VAR=TIMEOUT:int:3600:Total time of HDD array testing
+# VAR=TESTTIME:int:3600:Total time of HDD array testing
 # VAR=LOGTIME:int:120:Time between progress updates
 # VAR=JOBS:int:16:Number of parallely running jobs during compile
 # VAR=STRESS_TREE:string:/usr/share/inquisitor/linux-2.6.22.5-31-stress.tar.gz:Tarball file containing stress test tree
 
 . /usr/share/inquisitor/functions-test
 
-make_arrays()
+MOUNTPOINT=`mktemp -d`
+
+# Cleanup
+exit_handler()
 {
-	if raid-wizard-optimal; then
-		detect_hdd_quantity
-		true
-	else
-		HDD_QUANTITY=0 #not to start testing cycles
-		test_failed
+	local rc=$?
+	trap - EXIT
+
+	if [ -d "$MOUNTPOINT" ]; then
+		clear_testing_environment
 	fi
+	exit $rc
+}
+trap exit_handler HUP PIPE INT QUIT TERM EXIT
+
+detect_hdd_quantity()
+{
+	sleep 5
+	HDD_QUANTITY=`hal-find-by-property --key=storage.drive_type --string=disk | wc -l`
+#	if [ "$HDD_QUANTITY" -gt 0 ]; then
+		TIME_PER_ARRAY=$(( $TESTTIME / $HDD_QUANTITY ))
+#	else
+#		TIME_PER_ARRAY=$(( $TESTTIME / 2 ))
+#	fi
 }
 
-prepare_source_tree()
+clear_testing_environment()
 {
-	local tree_root=$1
+	cd /
+	umount -f $tree_root
+	rm -rf $tree_root
+}
 
-	cd $tree_root
-	tar xzf "$STRESS_TREE" >/dev/null 2>&1 || test_failed
+array_stress_check()
+{
+	local array=$1
+
+	prepare_array_for_test $array
+
+	START=`date "+%s"`
+	LAST_LOG_TIME=$TOTAL_START
+
+	while true; do
+		TIME=`date "+%s"`
+		if $(( $TIME - $START > $TIME_PER_ARRAY )); then
+			clear_testing_environment
+			break
+		else
+			make clean >/dev/null 2>&1 && \
+			make -j $JOBS fs >/dev/null 2>&1 || test_failed "Make error"
+		fi
+
+		if $(( $TIME - $LAST_LOG_TIME > $LOGTIME )); then
+			test_progress $(( $TIME - $TOTAL_START )) $TESTTIME
+			LAST_LOG_TIME=$TIME
+		fi
+	done
+}
+
+prepare_array_for_test()
+{
+	local array=$1
+
+	mke2fs -m0 -F $array >/dev/null 2>&1 || test_failed "Disk write error"
+	mount -t ext2 $array $MOUNTPOINT
+
+	cd $MOUNTPOINT
+	tar xzf "$STRESS_TREE" >/dev/null 2>&1 || test_failed "Untaring error"
+
 	tree_name=`basename "$STRESS_TREE" .tar.gz`
-	cd "$tree_name"
+	cd $tree_name
 
 	#is it linux source?
 	if echo "$tree_name" | grep '^linux' ; then
@@ -40,85 +92,22 @@ prepare_source_tree()
 	fi
 }
 
-detect_hdd_quantity()
-{
-	sleep 5
-	HDD_QUANTITY=`hal-find-by-property --key=storage.drive_type --string=disk | wc -l`
-	if [ "$HDD_QUANTITY" -gt 0 ]; then
-		TIME_PER_ARRAY=$(( $TIMEOUT / $HDD_QUANTITY ))
-	else
-		TIME_PER_ARRAY=$(( $TIMEOUT / 2 ))
-	fi
-}
+#Making arrays
+if raid-wizard-optimal; then
+	detect_hdd_quantity
+	true
+else
+	test_failed "No HDDs"
+	return
+fi
 
-temporary_hddarr_jobs_check()
-{
-	TOTAL_MEMORY=$(( `grep MemTotal /proc/meminfo | awk '{print $2}'` / 1024 ))
-
-	[ "$TOTAL_MEMORY" -lt 512 ] && JOBS=4 || true
-}
-
-prepare_array_for_test()
-{
-	local array=$1
-	local mountpoint=$2
-
-	mke2fs -m0 -F $array >/dev/null 2>&1 || test_failed
-	mount -t ext2 $array $mountpoint
-	prepare_source_tree $mountpoint
-}
-
-test_command_itself()
-{
-	make clean >/dev/null 2>&1 && \
-	make -j $JOBS fs >/dev/null 2>&1 || test_failed
-}
-
-clear_testing_environment()
-{
-	local tree_root=$1
-
-	cd /
-	rm -rf $tree_root/*
-	umount $tree_root
-	rmdir $tree_root
-}
-
-array_stress_check()
-{
-	local array=$1
-	local mountpoint=`mktemp -d`
-
-	prepare_array_for_test $array $mountpoint
-
-	START=`date "+%s"`
-	LAST_LOG_TIME=$TOTAL_START
-
-	while true; do
-		TIME=`date "+%s"`
-		if $(( $TIME - $START > $TIME_PER_ARRAY )); then
-			clear_testing_environment $MOUNTPOINT
-			break
-		else
-			test_command_itself
-		fi
-
-		if $(( $TIME - $LAST_LOG_TIME > $LOGTIME )); then
-			test_progress $(( $TIME - $TOTAL_START )) $TIMEOUT
-			LAST_LOG_TIME=$TIME
-		fi
-	done
-}
-
-make_arrays
-[ "$HDD_QUANTITY" -eq 0 ] && return
-temporary_hddarr_jobs_check
+#TEMPORARY checking for correct number of JOBS
+TOTAL_MEMORY=$(( `grep MemTotal /proc/meminfo | awk '{print $2}'` / 1024 ))
+[ "$TOTAL_MEMORY" -lt 512 ] && JOBS=4 || true
 
 TOTAL_START=`date "+%s"`
-test_started $TIMEOUT
+test_promise_time $TESTTIME
 
 for i in `get_harddrives_list`; do
 	array_stress_check $i
 done
-
-test_succeeded
diff --git a/client/test/net b/client/test/net
--- a/client/test/net
+++ b/client/test/net
@@ -12,17 +12,30 @@
 
 . /usr/share/inquisitor/functions-test
 
-print_read_message '!!! THIS IS DEVELOPMENT TEST !!!'
+print_red_message '!!! THIS IS DEVELOPMENT TEST !!!'
 
-detect_nic_quantity()
+# Cleanup
+exit_handler()
 {
-	NIC_QUANTITY=`cat /proc/net/dev | grep eth | wc -l`
-}
+	local rc=$?
+	trap - EXIT
 
-detect_first_nic()
-{
-	FIRST_NIC=`ip route | grep default | awk '{print $NF}' | sed 's/eth//'`
+	ip route del default
+	ip link set eth${FIRST_NIC} up
+	ip neigh flush
+	ip route add default via $SERVER dev eth${FIRST_NIC}
+	ip neigh flush
+	sleep 5
+
+	for i in `seq 0 $(( $NIC_QUANTITY - 1 ))`; do
+		if [ $i -ne "$FIRST_NIC" ]; then
+			ip link set eth${i} down
+		fi
+	done
+
+	exit $rc
 }
+trap exit_handler HUP PIPE INT QUIT TERM EXIT
 
 test_nic()
 {
@@ -36,24 +49,22 @@ test_nic()
 	sleep 5
 
 	for i in `seq 0 $(( $NIC_QUANTITY - 1 ))`; do
-		if [ "nic_number" -ne $i ]; then
-			ip link set eth${nic_number} down
+		if [ "$nic_number" -ne $i ]; then
+			ip link set eth${i} down
 		fi
 	done
 
-	[ `wget -T $TIMEOUT --quiet -O - http://${SERVER}/test_file | md5sum -b | awk '{print $1}'` = $MD5 ] && FLAG=1 || FLAG=0
+	[ `wget -T $TIMEOUT --quiet -O - http://${SERVER}/test_file | md5sum -b | awk '{print $1}'` = $MD5 ] || test_failed "NIC eth${i} test failed"
 }
 
-detect_nic_quantity
+NIC_QUANTITY=`cat /proc/net/dev | grep eth | wc -l`
 [ "$NIC_QUANTITY" -eq 0 ] && return
+FIRST_NIC=`ip route | grep default | awk '{print $NF}' | sed 's/eth//'`
 
 for i in `seq 0 $(( $NIC_QUANTITY - 1 ))`; do
 if [ "$FIRST_NIC" -ne $i ]; then
 	ip route del default
 	test_nic $i
-	if [ "$FLAG" -eq 0 ]; then
-		true # ?
-	fi
 fi
 done
 
