Some parsing of modem's ATI answer for detects.
git-svn-id: svn+ssh://svn.code.sf.net/p/inq/svn/trunk@1513 74654560-fcd8-4db3-b3c5-4c63e7cb38b4

diff --git a/client/test/gprs-modem b/client/test/gprs-modem
--- a/client/test/gprs-modem
+++ b/client/test/gprs-modem
@@ -16,36 +16,49 @@
 exit_handler()
 {
 	[ -f "$TMP_DIR/imei" ] && rm -f $TMP_DIR/imei
+	[ -f "$TMP_DIR/ati" ] && rm -f $TMP_DIR/ati
 	[ -d "$TMP_DIR" ] && rmdir $TMP_DIR
 }
+
+TMP_DIR=`mktemp -d`
 
 # Try to set modem speed to 115200 (if it's at 9600). We'll fail if it's
 # already at 115200, so ignore it - we'll check for the final state at
 # next step.
-print_green_message "Transition from 9600 to 115200"
+echo -n "Transition from 9600 to 115200..."
 stty 9600 -F $DEV
-chat -t $CHAT_TIMEOUT -Vs '' AT OK-AT-OK AT+IPR=115200 OK <$DEV >$DEV || {
-	print_red_message "Failed to set modem from 9600 to 115200 speed"
-	true
+chat -t $CHAT_TIMEOUT -Vs '' AT OK-AT-OK AT+IPR=115200 OK <$DEV >$DEV 2>/dev/null || {
+	echo -n "failed to set modem from 9600 to 115200 speed"
+	echo_failure
 }
+echo_success
 
 sleep 1
-
-print_green_message "Check for proper answer from modem"
+echo -n "Check for proper answer from modem..."
 stty 115200 -F $DEV
 sleep 1
-chat -t $CHAT_TIMEOUT -Vs '' AT OK-AT-OK ATI $ANSWER_ATI <$DEV >$DEV || \
+chat -t $CHAT_TIMEOUT -Vs '' AT OK-AT-OK ATI $ANSWER_ATI \
+	<$DEV >$DEV \
+	2>$TMP_DIR/ati ||
 	test_failed 'Proper answer from modem'
+echo_success
+
+# Parse ATI's answer
+# Assume that it is two or three strings output with vendor, model and
+# some revision on them
+ati=`sed -n '/^ATI/,/^OK/p' < $TMP_DIR/ati | sed '/^OK/d;/^ATI$/d;/^$/d'`
+component_vendor=`echo "$ati" | sed -n '1p'`
+component_model=`echo "$ati" | sed -n '2p'`
+component_version=`echo "$ati" | sed -n '3p' | sed 's/[Rr]evision://'`
 
 sleep 1
-
-print_green_message "Getting IMEI"
-TMP_DIR=`mktemp -d`
+echo -n "Getting IMEI... "
 chat -t $CHAT_TIMEOUT -Vs '' AT OK-AT-OK AT+GSN OK <$DEV >$DEV 2>$TMP_DIR/imei \
 	|| test_failed 'Getting IMEI'
 IMEI=`sed -ne '/^[0-9][0-9]*$/ p' <$TMP_DIR/imei`
-print_green_message "IMEI: $IMEI"
+echo -n "$IMEI"
+echo_success
 
-add_component 'GPRS Modem' 'SIMCOM_Ltd' 'SIMCOM_SIM100S' "$IMEI" ""
+add_component 'GPRS Modem' "$component_vendor" "$component_model" "$IMEI" "$component_version"
 
 test_succeeded
