Mistakenly redirected stderr not to right direction.
git-svn-id: svn+ssh://svn.code.sf.net/p/inq/svn/trunk@1772 74654560-fcd8-4db3-b3c5-4c63e7cb38b4

diff --git a/client/main/inq-ipmitool b/client/main/inq-ipmitool
--- a/client/main/inq-ipmitool
+++ b/client/main/inq-ipmitool
@@ -4,12 +4,12 @@
 
 die()
 {
-	echo $* 2>&1 >$DEBUG_TTY
+	echo $* >$DEBUG_TTY 2>&1
 	exit 0
 }
 
 BINARY="ipmitool"
-which $BINARY 2>&1 >/dev/null || die "$0: $BINARY not found, exiting"
+which $BINARY >/dev/null 2>&1 || die "$0: $BINARY not found, exiting"
 
 [ -c /dev/ipmi0 -o -c /dev/ipmi/0 -o -c /dev/ipmidev/0 ] \
 || die "$0: IPMI device file not found, exiting"
