* add_software_component method won't do any redirect or HTML   rendering as there is no need in it * Added executable_arch function * Created inq-software-detect for launching all software detects * Created add_software_component method in client's communication * Added bunch of simple detects
git-svn-id: svn+ssh://svn.code.sf.net/p/inq/svn/trunk@1291 74654560-fcd8-4db3-b3c5-4c63e7cb38b4

diff --git a/client/communication/rest b/client/communication/rest
--- a/client/communication/rest
+++ b/client/communication/rest
@@ -52,6 +52,18 @@ submit_additional_components()
 	[ -r "$1" ] && curl -f --data list=\""`cat $1 `"\" -X POST "$REST_SERVER/computers/submit_additional_components/$COMPUTER_ID.xml"
 }
 
+add_software_component()
+{
+	local name=`echo -n "$1" | ruby -e 'require "cgi"; print CGI::escape($stdin.read)'`
+	local arch=$2
+	local version=`echo -n "$3" | ruby -e 'require "cgi"; print CGI::escape($stdin.read)'`
+
+	if ! curl -sf "$REST_SERVER/computers/add_software_component/$COMPUTER_ID?name=$name&arch=$arch&version=$version"; then
+		echo 'add_software_component: failed to submit'
+		return 1
+	fi
+}
+
 # Mark current testing as finished
 testing_finished()
 {
