Added monitoring REST submission in client and server
git-svn-id: svn+ssh://svn.code.sf.net/p/inq/svn/trunk@617 74654560-fcd8-4db3-b3c5-4c63e7cb38b4

diff --git a/client/communication/rest b/client/communication/rest
--- a/client/communication/rest
+++ b/client/communication/rest
@@ -98,3 +98,11 @@ benchmark_submit_string()
 		return 1
 	fi
 }
+
+monitoring_submit()
+{
+	if ! curl -sf "$REST_SERVER/computers/monitoring_submit/$COMPUTER_ID?monitoring_id=$MONITORING_ID&key=$1&value=$2"; then
+		echo "monitoring_submit: failed to submit ${MONITORING_NAME}"
+		return 1
+	fi
+}
