Added set_profile to force a specific profile from a client; misc formatting fixes
git-svn-id: svn+ssh://svn.code.sf.net/p/inq/svn/trunk@623 74654560-fcd8-4db3-b3c5-4c63e7cb38b4

diff --git a/client/communication/rest b/client/communication/rest
--- a/client/communication/rest
+++ b/client/communication/rest
@@ -98,6 +98,13 @@ benchmark_submit_string()
 		return 1
 	fi
 }
+set_profile()
+{
+	if ! curl -sf "$REST_SERVER/computers/set_profile/$COMPUTER_ID?profile=$1"; then
+		echo 'set_profile: failed to set'
+		return 1
+	fi
+}
 
 monitoring_submit()
 {
