* monitoring_submit_multiple() implemented * odd_read test now uses it, that highly increases performance * #293 closed
git-svn-id: svn+ssh://svn.code.sf.net/p/inq/svn/trunk@928 74654560-fcd8-4db3-b3c5-4c63e7cb38b4

diff --git a/client/communication/rest b/client/communication/rest
--- a/client/communication/rest
+++ b/client/communication/rest
@@ -118,6 +118,14 @@ monitoring_submit()
 	fi
 }
 
+monitoring_submit_multiple()
+{
+	if ! curl -sf -F monitoring_data=@$1 "$REST_SERVER/computers/monitoring_submit_multiple/$COMPUTER_ID?monitoring_id=$MONITORING_ID"; then
+		echo "monitoring_submit_multiple: failed to submit ${MONITORING_NAME}"
+		return 1
+	fi
+}
+
 require_attention()
 {
 	return 0
