Added support for running tests, scheduled using planner
git-svn-id: svn+ssh://svn.code.sf.net/p/inq/svn/trunk@472 74654560-fcd8-4db3-b3c5-4c63e7cb38b4

diff --git a/client/communication/rest b/client/communication/rest
--- a/client/communication/rest
+++ b/client/communication/rest
@@ -10,6 +10,14 @@ get_id_by_macs()
 	fi
 }
 
+plan_test_script()
+{
+	if ! curl -sf "$REST_SERVER/computers/plan/$COMPUTER_ID" >$HOME/test_script; then
+		echo 'Unable to get testing plan'
+		return 1
+	fi
+}
+
 test_stage_advance()
 {
 	STAGE=$1
