Forgotten example values removing.
git-svn-id: svn+ssh://svn.code.sf.net/p/inq/svn/trunk@788 74654560-fcd8-4db3-b3c5-4c63e7cb38b4

diff --git a/client/communication/rest b/client/communication/rest
--- a/client/communication/rest
+++ b/client/communication/rest
@@ -140,14 +140,10 @@ dismiss_attention()
 
 get_needed_firmwares_list()
 {
-	# Example values
-	echo "Motherboard::08011::megabios.img"
-	echo "RAID::1.22::raidbios.img"
-
-	#if ! curl -sf "$REST_SERVER/computers/needed_firmwares_list/$COMPUTER_ID"; then
-	#	echo "get_needed_firmwares_list: failed to get list"
-	#	return 1
-	#fi
+	if ! curl -sf "$REST_SERVER/computers/needed_firmwares_list/$COMPUTER_ID"; then
+		echo "get_needed_firmwares_list: failed to get list"
+		return 1
+	fi
 }
 
 boot_from_image()
